name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.18' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true

      - name: Generate
        run: go generate ./...

      - name: Upload Generated Code
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Goater-Generated-${{ matrix.go-version }}
          path: '**/*_goat.go'

      - name: Test
        run: go test ./...